"""Wheeled VQR model configuration for the pivot task."""

from .robot_cfg import (
    ARTICULATION_BODY_NAMES,
    ARTICULATION_JOINT_NAMES,
    BASE_LINK_NAME,
    CONTROLLED_JOINT_NAMES,
    LEG_JOINT_NAMES,
    LIFTED_WHEEL_NAMES,
    SUPPORT_WHEEL_NAMES,
    VQR_CFG,
    WHEEL_BODY_NAMES,
    WHEEL_JOINT_NAMES,
)

__all__ = [
    "ARTICULATION_BODY_NAMES",
    "ARTICULATION_JOINT_NAMES",
    "BASE_LINK_NAME",
    "CONTROLLED_JOINT_NAMES",
    "LEG_JOINT_NAMES",
    "LIFTED_WHEEL_NAMES",
    "SUPPORT_WHEEL_NAMES",
    "VQR_CFG",
    "WHEEL_BODY_NAMES",
    "WHEEL_JOINT_NAMES",
]
